// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mirror.Application.DatabaseContext;

#nullable disable

namespace Mirror.Application.Migrations
{
    [DbContext(typeof(MirrorContext))]
    [Migration("20250111113134_AddedFilePath")]
    partial class AddedFilePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mirror.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "imageContentType");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "imageName");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "filePath");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "saved");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.Property<Guid?>("UserMemoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "memoryId");

                    b.HasKey("Id");

                    b.HasIndex("UserMemoryId");

                    b.ToTable("Images");

                    b.HasAnnotation("Relational:JsonPropertyName", "memoryImages");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<bool?>("IsAchieved")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isAchieved");

                    b.Property<double>("PercentageAchieved")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "percentageAchieved");

                    b.Property<string>("ProgressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "progressName");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "saved");

                    b.Property<double>("TrackedDays")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "trackedDays");

                    b.Property<string>("TrackingProgressDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "trackingProgressDay");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Progresses");

                    b.HasAnnotation("Relational:JsonPropertyName", "progress");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89e39006-abb0-4d6c-a045-e36a1aa4c62e"),
                            Description = "Cutting body fat",
                            PercentageAchieved = 63.0,
                            ProgressName = "Weight",
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(7904),
                            TrackedDays = 0.0,
                            TrackingProgressDay = "Tuesday",
                            UserId = new Guid("36165a94-1a9c-43dd-bf13-97a4e61e8b89")
                        },
                        new
                        {
                            Id = new Guid("42f99827-ca6e-4f5b-a31f-a99458c2e344"),
                            Description = "Training to Marathon",
                            PercentageAchieved = 47.0,
                            ProgressName = "Time",
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(7918),
                            TrackedDays = 0.0,
                            TrackingProgressDay = "Thursday",
                            UserId = new Guid("6d3080d4-5dbf-4549-8ac1-77713785de2a")
                        });
                });

            modelBuilder.Entity("Mirror.Domain.Entities.ProgressValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("ProgressColumnHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "progressColumnHead");

                    b.Property<string>("ProgressColumnValue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "column-value");

                    b.Property<int>("ProgressDate_Day")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "day");

                    b.Property<int>("ProgressDate_Month")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "month");

                    b.Property<int>("ProgressDate_Year")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.Property<Guid>("ProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "saved");

                    b.HasKey("Id");

                    b.HasIndex("ProgressId");

                    b.ToTable("ProgressValues");

                    b.HasAnnotation("Relational:JsonPropertyName", "progressValues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8b69ace-2e35-4058-97cd-6578bff6f03d"),
                            ProgressColumnHead = "Weight",
                            ProgressColumnValue = "71",
                            ProgressDate_Day = 6,
                            ProgressDate_Month = 8,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("89e39006-abb0-4d6c-a045-e36a1aa4c62e"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8226)
                        },
                        new
                        {
                            Id = new Guid("7c0a34ba-acf1-48d6-a9d7-ea03aeb628ed"),
                            ProgressColumnHead = "Weight",
                            ProgressColumnValue = "72",
                            ProgressDate_Day = 10,
                            ProgressDate_Month = 8,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("89e39006-abb0-4d6c-a045-e36a1aa4c62e"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8236)
                        },
                        new
                        {
                            Id = new Guid("5728290d-19ef-492c-b5c0-88b5ae372601"),
                            ProgressColumnHead = "Weight",
                            ProgressColumnValue = "73",
                            ProgressDate_Day = 12,
                            ProgressDate_Month = 8,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("89e39006-abb0-4d6c-a045-e36a1aa4c62e"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8241)
                        },
                        new
                        {
                            Id = new Guid("ee26e24d-47b9-4181-be70-425d95d230e6"),
                            ProgressColumnHead = "Time",
                            ProgressColumnValue = "25:17",
                            ProgressDate_Day = 5,
                            ProgressDate_Month = 1,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("42f99827-ca6e-4f5b-a31f-a99458c2e344"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8259)
                        },
                        new
                        {
                            Id = new Guid("94e3550e-a874-4235-9692-2b2a2d61b549"),
                            ProgressColumnHead = "Time",
                            ProgressColumnValue = "26:18",
                            ProgressDate_Day = 10,
                            ProgressDate_Month = 1,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("42f99827-ca6e-4f5b-a31f-a99458c2e344"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8263)
                        },
                        new
                        {
                            Id = new Guid("f1d7ecba-22e5-474c-bcad-d8d520436a68"),
                            ProgressColumnHead = "Time",
                            ProgressColumnValue = "24:05",
                            ProgressDate_Day = 15,
                            ProgressDate_Month = 1,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("42f99827-ca6e-4f5b-a31f-a99458c2e344"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8268)
                        },
                        new
                        {
                            Id = new Guid("9f8a668a-31ef-4f07-b0f4-ab3e13e03fb0"),
                            ProgressColumnHead = "Time",
                            ProgressColumnValue = "27:18",
                            ProgressDate_Day = 20,
                            ProgressDate_Month = 1,
                            ProgressDate_Year = 2024,
                            ProgressId = new Guid("42f99827-ca6e-4f5b-a31f-a99458c2e344"),
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(8273)
                        });
                });

            modelBuilder.Entity("Mirror.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "saved");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36165a94-1a9c-43dd-bf13-97a4e61e8b89"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "hashedpassword123",
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(7459)
                        },
                        new
                        {
                            Id = new Guid("6d3080d4-5dbf-4549-8ac1-77713785de2a"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "hashedpassword456",
                            SavedDate = new DateTime(2025, 1, 11, 11, 31, 32, 553, DateTimeKind.Utc).AddTicks(7468)
                        });
                });

            modelBuilder.Entity("Mirror.Domain.Entities.UserMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("MemoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "memoryName");

                    b.Property<string>("Reminder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "reminder");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "saved");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.Image", b =>
                {
                    b.HasOne("Mirror.Domain.Entities.UserMemory", "UserMemory")
                        .WithMany("Images")
                        .HasForeignKey("UserMemoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserMemory");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.Progress", b =>
                {
                    b.HasOne("Mirror.Domain.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.ProgressValue", b =>
                {
                    b.HasOne("Mirror.Domain.Entities.Progress", "Progress")
                        .WithMany("ProgressValue")
                        .HasForeignKey("ProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.UserMemory", b =>
                {
                    b.HasOne("Mirror.Domain.Entities.User", "User")
                        .WithMany("Memories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.Progress", b =>
                {
                    b.Navigation("ProgressValue");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.User", b =>
                {
                    b.Navigation("Memories");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("Mirror.Domain.Entities.UserMemory", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
